name: 'Arduino IDE for GitHub Actions'
description: 'Installs ArduinoIDE and adds some cool tools to build your sketches'
author: 'me-no-dev'
branding:
  icon: upload-cloud
  color: green
inputs:
  ide_path:
    description: 'Location where to install Arduino IDE (Default: $HOME/arduino-ide)'
    required: false
    default: '$HOME/arduino-ide'
  usr_path:
    description: 'Location where user sketches, libraries and etc. are (Default: $HOME/Arduino)'
    required: false
    default: '$HOME/Arduino'
runs:
  using: 'docker'
  image: 'Dockerfile'